### ISSUE TITLE
Test sentence split method

### ISSUE THREAD

**Issue by accraze** [accraze/python-ia-markov#19]
We should add some unit tests for the [`MarkovModel.sentence_split`](https://github.com/accraze/python-ia-markov/blob/master/src/ia_markov/markov.py#L33) method.

Coverage: https://codecov.io/gh/accraze/python-ia-markov/src/master/src/ia_markov/markov.py#L37

**Comment by danhenriquesc** [comment]
I'll take this!

**Comment by danhenriquesc** [comment]
https://github.com/accraze/python-ia-markov/pull/23

**Comment by accraze** [comment]
closed by #23
